### ISSUE TITLE
delete host: NameError: name 'y' is not defined

### ISSUE THREAD

**Issue by flynn1973** [phamhongviet/ansible-inventory-mysql#1]
while testing your script i found the following. not shure if i'm doing something wrong or its
some kind of bug.

```
root@lpgaixmgmtlx01:/root/ansible-dynamic-inventory-mysql>./inventoryctl.py host -H TESTHOST -d
[Command]: host
Are you sure you want to delete the host: TESTHOST[TESTHOST] ?!
After deleting the data will not be restored!!  [y/n]: y
Traceback (most recent call last):
  File "./inventoryctl.py", line 552, in <module>
    InventoryCtl()
  File "./inventoryctl.py", line 38, in __init__
    self.run_command()
  File "./inventoryctl.py", line 115, in run_command
    self._cmd_host()
  File "./inventoryctl.py", line 135, in _cmd_host
    hostdata['host'], hostdata['hostname'])):
  File "./inventoryctl.py", line 527, in _prompt
    val = input()
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined
```

**Comment by flynn1973** [comment]
oops sorry wrong project...please ignore.
